// <auto-generated by build/package-toolbox.ps1>
// This file is regenerated by the toolbox packaging script. The committed copy is an empty stub so
// that the project still compiles in dev builds without staged resources. CI / local toolbox builds
// will overwrite it with the full eight-entry manifest.
namespace HUnityAutoTranslator.Toolbox.Core.Installation;

internal static class EmbeddedAssetManifest
{
    public static readonly IReadOnlyList<EmbeddedAsset> Entries = Array.Empty<EmbeddedAsset>();
}
