using HUnityAutoTranslator.Core.Prompts;

namespace HUnityAutoTranslator.Core.Configuration;

public sealed record RuntimeConfig(
    bool Enabled,
    string TargetLanguage,
    TranslationStyle Style,
    ProviderProfile Provider,
    string HttpHost,
    int HttpPort,
    bool AutoOpenControlPanel,
    int MaxConcurrentRequests,
    int RequestsPerMinute,
    int MaxBatchCharacters,
    TimeSpan ScanInterval,
    int MaxScanTargetsPerTick,
    int MaxWritebacksPerFrame,
    int RequestTimeoutSeconds,
    string ReasoningEffort,
    string OutputVerbosity,
    string DeepSeekThinkingMode,
    double? Temperature,
    string? CustomInstruction,
    string? CustomPrompt,
    int MaxSourceTextLength,
    bool IgnoreInvisibleText,
    bool SkipNumericSymbolText,
    bool EnableCacheLookup,
    bool ManualEditsOverrideAi,
    bool ReapplyRememberedTranslations,
    int CacheRetentionDays,
    bool EnableUgui,
    bool EnableTmp,
    bool EnableImgui)
{
    public static RuntimeConfig CreateDefault()
    {
        return new RuntimeConfig(
            Enabled: true,
            TargetLanguage: "zh-Hans",
            Style: TranslationStyle.Localized,
            Provider: ProviderProfile.DefaultOpenAi(),
            HttpHost: "127.0.0.1",
            HttpPort: 48110,
            AutoOpenControlPanel: true,
            MaxConcurrentRequests: 4,
            RequestsPerMinute: 60,
            MaxBatchCharacters: 1800,
            ScanInterval: TimeSpan.FromMilliseconds(750),
            MaxScanTargetsPerTick: 256,
            MaxWritebacksPerFrame: 32,
            RequestTimeoutSeconds: 30,
            ReasoningEffort: "low",
            OutputVerbosity: "low",
            DeepSeekThinkingMode: "enabled",
            Temperature: null,
            CustomInstruction: null,
            CustomPrompt: null,
            MaxSourceTextLength: 2000,
            IgnoreInvisibleText: true,
            SkipNumericSymbolText: true,
            EnableCacheLookup: true,
            ManualEditsOverrideAi: true,
            ReapplyRememberedTranslations: true,
            CacheRetentionDays: 365,
            EnableUgui: true,
            EnableTmp: true,
            EnableImgui: true);
    }
}
