namespace HUnityAutoTranslator.Toolbox;

internal static class ToolboxHtml
{
    // <auto-generated by build/package-toolbox.ps1>
    public const string Document = """
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>HUnityAutoTranslator 工具箱</title>
</head>
<body>
  <div id="app">工具箱界面尚未生成，请运行 build/package-toolbox.ps1。</div>
</body>
</html>
""";
}
