using HUnityAutoTranslator.Core.Configuration;
using HUnityAutoTranslator.Core.Prompts;

namespace HUnityAutoTranslator.Core.Control;

public sealed record ControlPanelState(
    bool Enabled,
    string TargetLanguage,
    string? GameTitle,
    string? AutomaticGameTitle,
    TranslationStyle Style,
    ProviderKind ProviderKind,
    string BaseUrl,
    string Endpoint,
    string Model,
    bool ApiKeyConfigured,
    string? ApiKeyPreview,
    bool AutoOpenControlPanel,
    string OpenControlPanelHotkey,
    string ToggleTranslationHotkey,
    string ForceScanHotkey,
    string ToggleFontHotkey,
    int QueueCount,
    int CacheCount,
    long CapturedTextCount,
    long QueuedTextCount,
    long InFlightTranslationCount,
    long CompletedTranslationCount,
    long TotalTokenCount,
    double AverageTranslationMilliseconds,
    double AverageCharactersPerSecond,
    int WritebackQueueCount,
    ProviderStatus ProviderStatus,
    IReadOnlyList<RecentTranslationPreview> RecentTranslations,
    int MaxConcurrentRequests,
    int EffectiveMaxConcurrentRequests,
    int RequestsPerMinute,
    int MaxBatchCharacters,
    int ScanIntervalMilliseconds,
    int MaxScanTargetsPerTick,
    int MaxWritebacksPerFrame,
    int RequestTimeoutSeconds,
    string ReasoningEffort,
    string OutputVerbosity,
    string DeepSeekThinkingMode,
    string? OpenAICompatibleCustomHeaders,
    string? OpenAICompatibleExtraBodyJson,
    double? Temperature,
    string? CustomPrompt,
    string DefaultSystemPrompt,
    PromptTemplateConfig PromptTemplates,
    PromptTemplateConfig DefaultPromptTemplates,
    TranslationQualityConfig TranslationQuality,
    int MaxSourceTextLength,
    bool IgnoreInvisibleText,
    bool SkipNumericSymbolText,
    bool EnableCacheLookup,
    bool EnableTranslationDebugLogs,
    bool EnableTranslationContext,
    int TranslationContextMaxExamples,
    int TranslationContextMaxCharacters,
    bool EnableGlossary,
    bool EnableAutoTermExtraction,
    int GlossaryMaxTerms,
    int GlossaryMaxCharacters,
    bool ManualEditsOverrideAi,
    bool ReapplyRememberedTranslations,
    bool EnableUgui,
    bool EnableTmp,
    bool EnableImgui,
    bool EnableFontReplacement,
    bool ReplaceUguiFonts,
    bool ReplaceTmpFonts,
    bool ReplaceImguiFonts,
    bool AutoUseCjkFallbackFonts,
    string? ReplacementFontName,
    string? ReplacementFontFile,
    string? AutomaticReplacementFontName,
    string? AutomaticReplacementFontFile,
    int FontSamplingPointSize,
    FontSizeAdjustmentMode FontSizeAdjustmentMode,
    double FontSizeAdjustmentValue,
    string? LastError,
    TextureImageTranslationConfig TextureImageTranslation,
    bool TextureImageApiKeyConfigured,
    LlamaCppConfig LlamaCpp,
    LlamaCppServerStatus LlamaCppStatus,
    IReadOnlyList<ProviderProfileState>? ProviderProfiles = null,
    string? ActiveProviderProfileId = null,
    string? ActiveProviderProfileName = null,
    ProviderKind? ActiveProviderProfileKind = null,
    string? ActiveProviderProfileModel = null,
    ProviderActivityPreview? ActiveTranslationProvider = null,
    IReadOnlyList<TextureImageProviderProfileState>? TextureImageProviderProfiles = null,
    string? ActiveTextureImageProviderProfileId = null,
    string? ActiveTextureImageProviderProfileName = null,
    string? ActiveTextureImageProviderProfileModel = null,
    SelfCheckReport? SelfCheck = null);
