using FluentAssertions;

namespace HUnityAutoTranslator.Core.Tests.Control;

public sealed class ControlPanelHtmlSourceTests
{
    [Fact]
    public void Control_panel_html_is_generated_from_vue_source()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("<auto-generated by build/package.ps1 -GeneratePanelOnly>");
        htmlSource.Should().Contain("data-app=\"hunity-control-panel\"");
        htmlSource.Should().Contain("id=\"app\"");
        htmlSource.Should().Contain("HUnityAutoTranslator");
    }

    [Fact]
    public void Generated_control_panel_does_not_depend_on_remote_assets()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().NotContain("https://cdn");
        htmlSource.Should().NotContain("http://cdn");
        htmlSource.Should().NotContain("unpkg.com");
        htmlSource.Should().NotContain("jsdelivr.net");
        htmlSource.Should().NotContain("fonts.googleapis.com");
    }

    [Fact]
    public void Local_http_server_exposes_glossary_and_translation_editor_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Plugin.cs"));

        serverSource.Should().Contain("path == \"/api/glossary\"");
        serverSource.Should().Contain("path == \"/api/translations/filter-options\"");
        serverSource.Should().Contain("path == \"/api/translations/retranslate\"");
        serverSource.Should().Contain("path == \"/api/translations/highlight\"");
        serverSource.Should().Contain("ParseTranslationFilterOptionsQuery");
        serverSource.Should().Contain("ParseColumnFilters");
        serverSource.Should().Contain("TranslationCacheColumns.EmptyValueMarker");
        pluginSource.Should().Contain("translation-glossary.sqlite");
        pluginSource.Should().Contain("SqliteGlossaryStore");
    }

    [Fact]
    public void Local_http_server_exposes_windows_font_picker_endpoint_without_persisting_config()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pickerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "WindowsFontFilePicker.cs"));

        serverSource.Should().Contain("context.Request.HttpMethod == \"POST\" && path == \"/api/fonts/pick\"");
        serverSource.Should().Contain("WindowsFontFilePicker.PickFontFile()");
        serverSource.Should().NotContain("_controlPanel.UpdateConfig(new UpdateConfigRequest(ReplacementFont");
        pickerSource.Should().Contain("SetApartmentState(ApartmentState.STA)");
        pickerSource.Should().Contain("IFileOpenDialog");
        pickerSource.Should().Contain("*.ttf;*.otf");
        pickerSource.Should().Contain("FontNameReader.TryReadFamilyName");
        pickerSource.Should().Contain("FontPickResult.Unsupported");
        pickerSource.Should().Contain("FontPickResult.Cancelled");
    }

    [Fact]
    public void Local_http_server_exposes_llamacpp_manual_control_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var managerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "LlamaCppServerManager.cs"));
        var commandBuilderSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Core", "Providers", "LlamaCppServerCommandBuilder.cs"));

        serverSource.Should().Contain("path == \"/api/llamacpp/start\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/stop\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/model/pick\"");
        serverSource.Should().Contain("WindowsLlamaCppModelFilePicker.PickModelFile()");
        commandBuilderSource.Should().Contain("\"--host\"");
        commandBuilderSource.Should().Contain("\"127.0.0.1\"");
        commandBuilderSource.Should().Contain("int port");
        managerSource.Should().Contain("GetFreeLoopbackPort");
        managerSource.Should().Contain("Release");
        managerSource.Should().Contain("Variant");
        managerSource.Should().Contain("backend.json");
        managerSource.Should().Contain("llama-server.exe");
        managerSource.Should().Contain("StopOwnedProcess");
    }

    [Fact]
    public void Translation_editor_save_publishes_manual_writeback_for_known_targets()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var highlighterSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextHighlighter.cs"));

        serverSource.Should().Contain("TryGetExistingTranslation(entry");
        serverSource.Should().Contain("PublishManualWriteback(entry, previousTranslatedText)");
        serverSource.Should().Contain("previousTranslatedText:");
        serverSource.Should().Contain("TryResolveTargetId");
        highlighterSource.Should().Contain("TryResolveTargetId");
    }

    [Fact]
    public void Font_replacement_service_retries_tmp_candidates_and_caches_failures()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        serviceSource.Should().Contain("_failedTmpFontAssetKeys");
        serviceSource.Should().Contain("ResolveTmpFontAsset");
        serviceSource.Should().Contain("EnumerateFontCandidates");
        serviceSource.Should().Contain("foreach (var candidate in EnumerateFontCandidates(config, key, context))");
        serviceSource.Should().Contain("TMP fallback font asset could not be created from any candidate");
        serviceSource.Should().Contain("Action<string?, string?> automaticFontFallbackReporter");
        serviceSource.Should().Contain("ReportAutomaticFontFallbacks(config);");
        serviceSource.Should().Contain("ResolveFirstUsableAutomaticFontFile");
    }

    [Fact]
    public void Font_replacement_automatic_candidates_preserve_priority_and_use_regular_face_for_variable_fonts()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        var candidateFileBlock = serviceSource[
            serviceSource.IndexOf("private static readonly string[] CandidateFontFiles", StringComparison.Ordinal)..
            serviceSource.IndexOf("private static readonly string[] TmpFontAssetTypeNames", StringComparison.Ordinal)];

        candidateFileBlock.Should().Contain(@"C:\Windows\Fonts\NotoSansSC-VF.ttf");
        candidateFileBlock.Should().Contain(@"C:\Windows\Fonts\Deng.ttf");
        candidateFileBlock.IndexOf(@"C:\Windows\Fonts\NotoSansSC-VF.ttf", StringComparison.Ordinal)
            .Should().BeLessThan(candidateFileBlock.IndexOf(@"C:\Windows\Fonts\simhei.ttf", StringComparison.Ordinal));
        candidateFileBlock.IndexOf(@"C:\Windows\Fonts\simhei.ttf", StringComparison.Ordinal)
            .Should().BeLessThan(candidateFileBlock.IndexOf(@"C:\Windows\Fonts\Deng.ttf", StringComparison.Ordinal));
        candidateFileBlock.Should().Contain(".ttf");
        candidateFileBlock.Should().NotContain(".ttc");
        serviceSource.Should().Contain("Noto Sans SC Regular");
        serviceSource.Should().Contain("Noto Serif SC Regular");
        serviceSource.Should().Contain("FontCandidate.Create(\"auto-file\"");
        serviceSource.Should().NotContain("FontCandidate.Create(\"auto-name\"");
    }

    private static string FindRepositoryFile(params string[] relativeSegments)
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "HUnityAutoTranslator.sln")))
        {
            directory = directory.Parent;
        }

        directory.Should().NotBeNull("tests should run from inside the repository checkout");
        return Path.Combine(new[] { directory!.FullName }.Concat(relativeSegments).ToArray());
    }
}
