using FluentAssertions;

namespace HUnityAutoTranslator.Core.Tests.Control;

public sealed class ControlPanelHtmlSourceTests
{
    [Fact]
    public void Control_panel_html_is_generated_from_vue_source()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("<auto-generated by build/package.ps1 -GeneratePanelOnly>");
        htmlSource.Should().Contain("data-app=\"hunity-control-panel\"");
        htmlSource.Should().Contain("id=\"app\"");
        htmlSource.Should().Contain("HUnityAutoTranslator");
    }

    [Fact]
    public void Generated_control_panel_does_not_depend_on_remote_assets()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().NotContain("https://cdn");
        htmlSource.Should().NotContain("http://cdn");
        htmlSource.Should().NotContain("unpkg.com");
        htmlSource.Should().NotContain("jsdelivr.net");
        htmlSource.Should().NotContain("fonts.googleapis.com");
    }

    [Fact]
    public void Generated_control_panel_embeds_local_brand_favicon()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("rel=\"icon\"");
        htmlSource.Should().Contain("data:image/x-icon;base64,");
        htmlSource.Should().NotContain("href=\"./branding/");
        htmlSource.Should().NotContain("href=\"/branding/");
    }

    [Fact]
    public void Generated_control_panel_does_not_expose_cache_retention_settings()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().NotContain("CacheRetentionDays");
        htmlSource.Should().NotContain("cacheRetentionDays");
    }

    [Fact]
    public void Local_http_server_exposes_glossary_and_translation_editor_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"));

        serverSource.Should().Contain("path == \"/api/glossary\"");
        serverSource.Should().Contain("path == \"/api/translations/filter-options\"");
        serverSource.Should().Contain("path == \"/api/translations/retranslate\"");
        serverSource.Should().Contain("path == \"/api/translations/highlight\"");
        serverSource.Should().Contain("ParseTranslationFilterOptionsQuery");
        serverSource.Should().Contain("ParseColumnFilters");
        serverSource.Should().Contain("TranslationCacheColumns.EmptyValueMarker");
        pluginSource.Should().Contain("translation-glossary.sqlite");
        pluginSource.Should().Contain("SqliteGlossaryStore");
    }

    [Fact]
    public void Local_http_server_exposes_windows_font_picker_endpoint_without_persisting_config()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pickerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "WindowsFontFilePicker.cs"));

        serverSource.Should().Contain("context.Request.HttpMethod == \"POST\" && path == \"/api/fonts/pick\"");
        serverSource.Should().Contain("WindowsFontFilePicker.PickFontFile()");
        serverSource.Should().NotContain("_controlPanel.UpdateConfig(new UpdateConfigRequest(ReplacementFont");
        pickerSource.Should().Contain("SetApartmentState(ApartmentState.STA)");
        pickerSource.Should().Contain("IFileOpenDialog");
        pickerSource.Should().Contain("*.ttf;*.otf");
        pickerSource.Should().Contain("FontNameReader.TryReadFamilyName");
        pickerSource.Should().Contain("FontPickResult.Unsupported");
        pickerSource.Should().Contain("FontPickResult.Cancelled");
    }

    [Fact]
    public void Local_http_server_exposes_llamacpp_manual_control_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var managerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "LlamaCppServerManager.cs"));
        var commandBuilderSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Core", "Providers", "LlamaCppServerCommandBuilder.cs"));

        serverSource.Should().Contain("path == \"/api/llamacpp/start\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/stop\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/benchmark\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/model/pick\"");
        serverSource.Should().Contain("WindowsLlamaCppModelFilePicker.PickModelFile()");
        serverSource.Should().Contain("BenchmarkAsync(_controlPanel.GetConfig()");
        serverSource.Should().Contain("_controlPanel.UpdateConfig(new UpdateConfigRequest(LlamaCpp:");
        commandBuilderSource.Should().Contain("\"--host\"");
        commandBuilderSource.Should().Contain("\"127.0.0.1\"");
        commandBuilderSource.Should().Contain("\"--metrics\"");
        commandBuilderSource.Should().Contain("int port");
        managerSource.Should().Contain("GetFreeLoopbackPort");
        managerSource.Should().Contain("CUDA_SCALE_LAUNCH_QUEUES");
        managerSource.Should().Contain("llama-bench.exe");
        managerSource.Should().Contain("llama-batched-bench.exe");
        managerSource.Should().Contain("Release");
        managerSource.Should().Contain("Variant");
        managerSource.Should().Contain("backend.json");
        managerSource.Should().Contain("llama-server.exe");
        managerSource.Should().Contain("StopOwnedProcess");
    }

    [Fact]
    public void Local_http_server_exposes_llamacpp_model_download_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"));

        serverSource.Should().Contain("path == \"/api/llamacpp/model/presets\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/model/download\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/model/download/cancel\"");
        serverSource.Should().Contain("_llamaCppModelDownloads.GetPresets()");
        serverSource.Should().Contain("_llamaCppModelDownloads.StartDownload(");
        serverSource.Should().Contain("_llamaCppModelDownloads.CancelDownload()");
        pluginSource.Should().Contain("LlamaCppModelDownloadManager");
        pluginSource.Should().Contain("Path.Combine(pluginDirectory, \"models\")");
    }

    [Fact]
    public void Translation_editor_save_publishes_manual_writeback_for_known_targets()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var highlighterSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextHighlighter.cs"));

        serverSource.Should().Contain("TryGetExistingTranslation(entry");
        serverSource.Should().Contain("PublishManualWriteback(entry, previousTranslatedText)");
        serverSource.Should().Contain("previousTranslatedText:");
        serverSource.Should().Contain("TryResolveTargetId");
        highlighterSource.Should().Contain("TryResolveTargetId");
    }

    [Fact]
    public void Font_replacement_service_retries_tmp_candidates_and_caches_failures()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        serviceSource.Should().Contain("_failedTmpFontAssetKeys");
        serviceSource.Should().Contain("ResolveTmpFontAsset");
        serviceSource.Should().Contain("EnumerateFontCandidates");
        serviceSource.Should().Contain("foreach (var candidate in EnumerateFontCandidates(config, key, context))");
        serviceSource.Should().Contain("无法用候选字体创建 TMP 后备字体");
        serviceSource.Should().Contain("Action<string?, string?> automaticFontFallbackReporter");
        serviceSource.Should().Contain("ReportAutomaticFontFallbacks(config);");
        serviceSource.Should().Contain("ResolveFirstUsableAutomaticFontFile");
        serviceSource.Should().Contain("FontProbeCharacters");
        serviceSource.Should().Contain("IsUsableReplacementFont(regularFont, size)");
        serviceSource.Should().Contain("font.RequestCharactersInTexture(new string(FontProbeCharacters), size)");
        serviceSource.Should().Contain("font.HasCharacter(character)");
    }

    [Fact]
    public void Tmp_font_replacement_directly_assigns_components_before_global_fallbacks()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        serviceSource.Should().Contain("SetTmpFont(component, fontAsset)");
        serviceSource.Should().Contain("AddTmpFallbackToComponentFont(component, fontAsset)");
        serviceSource.Should().Contain("PopulateTmpFontAsset(fontAsset, component)");
        serviceSource.Should().Contain("method.Name == \"TryAddCharacters\"");
        serviceSource.Should().Contain("fallbackFontAssetTable");
        serviceSource.Should().Contain("m_FallbackFontAssetTable");
        serviceSource.Should().Contain("CollectionAdd(fallbackTable, fallbackFontAsset)");
        serviceSource.Should().Contain("AddTmpFallback(fontAsset)");
        serviceSource.Should().Contain("SetField(component, \"m_fontAsset\", fontAsset)");
        serviceSource.Should().Contain("SetField(component, \"m_currentFontAsset\", fontAsset)");
        serviceSource.Should().Contain("SetProperty(component, \"fontAsset\", fontAsset)");
        serviceSource.Should().Contain("SetProperty(component, \"fontSharedMaterial\", material)");
        serviceSource.Should().Contain("SetField(component, \"m_hasFontAssetChanged\", true)");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(component, \"LoadFontAsset\")");
        serviceSource.Should().Contain("SetProperty(component, \"havePropertiesChanged\", true)");
        serviceSource.Should().Contain("SetField(component, \"m_havePropertiesChanged\", true)");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(fontAsset, \"ReadFontAssetDefinition\")");
        serviceSource.Should().Contain("RegisterTmpFontAsset(fontAsset)");
        serviceSource.Should().Contain("MaterialReferenceManager");
        serviceSource.Should().Contain("method.Name == \"AddFontAsset\"");
        serviceSource.Should().Contain("InvokeSetter(instance, propertyName, value)");
        serviceSource.Should().Contain("method.Name == $\"get_{propertyName}\"");
        serviceSource.Should().Contain("method.Name == setterName");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(component, \"SetAllDirty\")");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(component, \"ForceMeshUpdate\")");
        serviceSource.Should().Contain("AppDomain.CurrentDomain.GetAssemblies()");
        serviceSource.Should().Contain("TMP 全局后备字体未安装");
        serviceSource.Should().Contain("TMP 组件字体直接替换失败");
        serviceSource.Should().Contain("TMP 组件字体后备表已挂载");
    }

    [Fact]
    public void Plugin_console_logs_use_simple_chinese_messages()
    {
        var logSources = new[]
        {
            FindRepositoryFile("src", "HUnityAutoTranslator.Core", "Queueing", "TranslationWorkerPool.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Plugin.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "TranslationWorkerHost.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "LlamaCppServerManager.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "SystemBrowserLauncher.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Hotkeys", "RuntimeHotkeyController.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Capture", "UguiTextScanner.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Capture", "TmpTextScanner.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Capture", "ImguiHookInstaller.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityMainThreadResultApplier.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextHighlighter.cs")
        };
        var combinedSource = string.Join("\n", logSources.Select(File.ReadAllText));
        var oldEnglishLogPhrases = new[]
        {
            "Control panel auto-open skipped because the URL is empty.",
            "Opened control panel in the system default browser",
            "Failed to open control panel in the system default browser",
            "HTTP panel listener failed",
            "Control panel config updated.",
            "Control panel API key cleared.",
            "Control panel API key configured.",
            "HTTP panel request failed",
            "llama.cpp server process exited.",
            "llama.cpp server started on random loopback port",
            "Stopping llama.cpp server failed",
            "Resumed ",
            "pending translation(s) from the persistent cache.",
            "Translation worker processed",
            "Writeback backlog",
            "Cache entries",
            "Translation worker failed",
            "Glossary extraction imported",
            "loaded. Control panel",
            "Persistent settings",
            "Translation cache",
            "Translation glossary",
            "Startup failed, plugin will stay inactive",
            "Control panel auto-open is disabled by settings.",
            "translated text result(s).",
            "targets were gone or changed before writeback.",
            "Highlight target disappeared before it could be drawn",
            "UGUI Text type not found; UGUI capture disabled.",
            "UGUI capture enabled.",
            "UGUI scan failed and will retry later",
            "TextMeshPro type not found; TMP capture disabled.",
            "TMP capture enabled with type",
            "TMP scan failed; TMP capture disabled",
            "IMGUI capture enabled.",
            "IMGUI hook installation failed; IMGUI capture disabled",
            "Failed to patch",
            "Runtime hotkey switched text display",
            "Runtime hotkey forced a full text scan",
            "Runtime hotkey switched text components",
            "Runtime hotkey restored original text component fonts",
            "TMP fallback font installed",
            "Font replacement skipped because the font could not be created",
            "Font replacement is enabled, but no usable CJK fallback font was found.",
            "TMP font replacement skipped because TextMeshPro settings or font asset APIs were not available.",
            "TMP fallback font asset could not be created from any candidate.",
            "Font size adjusted for",
            "Translation output rejected",
            "Translation provider failed",
            "Source preview",
            "unknown error"
        };

        combinedSource.Should().NotContainAny(oldEnglishLogPhrases);
    }

    [Fact]
    public void Font_replacement_automatic_candidates_preserve_priority_and_use_regular_face_for_variable_fonts()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        var candidateFileBlock = serviceSource[
            serviceSource.IndexOf("private static readonly string[] CandidateFontFiles", StringComparison.Ordinal)..
            serviceSource.IndexOf("private static readonly string[] TmpFontAssetTypeNames", StringComparison.Ordinal)];

        candidateFileBlock.Should().Contain(@"C:\Windows\Fonts\NotoSansSC-VF.ttf");
        candidateFileBlock.Should().Contain(@"C:\Windows\Fonts\Deng.ttf");
        candidateFileBlock.IndexOf(@"C:\Windows\Fonts\simhei.ttf", StringComparison.Ordinal)
            .Should().BeLessThan(candidateFileBlock.IndexOf(@"C:\Windows\Fonts\Deng.ttf", StringComparison.Ordinal));
        candidateFileBlock.IndexOf(@"C:\Windows\Fonts\Deng.ttf", StringComparison.Ordinal)
            .Should().BeLessThan(candidateFileBlock.IndexOf(@"C:\Windows\Fonts\NotoSansSC-VF.ttf", StringComparison.Ordinal));
        candidateFileBlock.Should().Contain(".ttf");
        candidateFileBlock.Should().NotContain(".ttc");
        serviceSource.Should().Contain("Noto Sans SC Regular");
        serviceSource.Should().Contain("Noto Serif SC Regular");
        serviceSource.Should().Contain("FontCandidate.Create(\"auto-file\"");
        serviceSource.Should().NotContain("FontCandidate.Create(\"auto-name\"");
    }

    private static string FindRepositoryFile(params string[] relativeSegments)
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "HUnityAutoTranslator.sln")))
        {
            directory = directory.Parent;
        }

        directory.Should().NotBeNull("tests should run from inside the repository checkout");
        return Path.Combine(new[] { directory!.FullName }.Concat(relativeSegments).ToArray());
    }
}
