using System.Text.RegularExpressions;
using FluentAssertions;

namespace HUnityAutoTranslator.Core.Tests.Control;

public sealed class ControlPanelHtmlSourceTests
{
    [Fact]
    public void Control_panel_html_is_generated_from_vue_source()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("<auto-generated by build/package.ps1 -GeneratePanelOnly>");
        htmlSource.Should().Contain("data-app=\"hunity-control-panel\"");
        htmlSource.Should().Contain("id=\"app\"");
        htmlSource.Should().Contain("HUnityAutoTranslator");
    }

    [Fact]
    public void Generated_control_panel_does_not_depend_on_remote_assets()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().NotContain("https://cdn");
        htmlSource.Should().NotContain("http://cdn");
        htmlSource.Should().NotContain("unpkg.com");
        htmlSource.Should().NotContain("jsdelivr.net");
        htmlSource.Should().NotContain("fonts.googleapis.com");
    }

    [Fact]
    public void Generated_control_panel_embeds_local_brand_favicon()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("rel=\"icon\"");
        htmlSource.Should().Contain("data:image/x-icon;base64,");
        htmlSource.Should().NotContain("href=\"./branding/");
        htmlSource.Should().NotContain("href=\"/branding/");
    }

    [Fact]
    public void Generated_control_panel_does_not_expose_cache_retention_settings()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().NotContain("CacheRetentionDays");
        htmlSource.Should().NotContain("cacheRetentionDays");
    }

    [Fact]
    public void Generated_control_panel_uses_compact_model_download_dialog_copy()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("模型下载");
        htmlSource.Should().Contain("model-download-dialog");
        htmlSource.Should().Contain("model-preset-list");
        htmlSource.Should().Contain("model-preset-card");
        htmlSource.Should().Contain("model-preset-license");
        htmlSource.Should().Contain("openLlamaCppModelDownload");
        htmlSource.Should().Contain(" · 速度 ");
        htmlSource.Should().Contain(" · 剩余 ");
        htmlSource.Should().Contain("计算中");
        Regex.IsMatch(htmlSource, @"(?s)\.model-preset-list\s*\{[^}]*grid-template-columns:\s*1fr;")
            .Should().BeTrue("the generated model preset list should stay single-column at every desktop width");
        Regex.IsMatch(htmlSource, @"(?s)\.model-preset-card\s*\{[^}]*grid-template-columns:\s*minmax\(0,1fr\);[^}]*place-content:\s*start stretch;")
            .Should().BeTrue("the generated model preset card content should use a full-width left-aligned grid track");
        Regex.IsMatch(htmlSource, @"(?s)\.model-preset-card>span\s*\{[^}]*width:\s*100%;[^}]*min-width:\s*0;[^}]*max-width:\s*100%;?")
            .Should().BeTrue("the generated model preset card text rows should fill the card width");
        Regex.IsMatch(htmlSource, @"(?s)@media \(max-width:780px\)[^{]*\{[^}]*\.model-preset-list,")
            .Should().BeFalse("single-column preset layout should not depend on the mobile breakpoint");
        htmlSource.Should().NotContain("兼容备选");
        htmlSource.Should().NotContain("魔塔");
        htmlSource.Should().NotContain("魔搭");
        htmlSource.Should().NotContain("<select id=\"llamaCppPreset\"");
    }

    [Fact]
    public void Generated_control_panel_uses_provider_profile_modal_editor()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("provider-editor-backdrop");
        htmlSource.Should().Contain("provider-editor-dialog");
        htmlSource.Should().Contain("provider-card-actions");
        htmlSource.Should().Contain("配置编辑器");
        htmlSource.Should().Contain("放弃未保存的服务商配置修改");
        htmlSource.Should().Contain("aria-labelledby");
        Regex.IsMatch(htmlSource, @"(?s)\.provider-profile-manager\s*\{[^}]*grid-template-columns:\s*1fr;")
            .Should().BeTrue("the provider profile manager should stay single-column at desktop widths");
        htmlSource.Should().NotContain("grid-template-columns:minmax(min(280px,100%),.82fr) minmax(0,1.6fr)");
    }

    [Fact]
    public void Local_http_server_exposes_glossary_and_translation_editor_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"));

        serverSource.Should().Contain("path == \"/api/glossary\"");
        serverSource.Should().Contain("path == \"/api/glossary/filter-options\"");
        serverSource.Should().Contain("path == \"/api/translations/filter-options\"");
        serverSource.Should().Contain("path == \"/api/translations/retranslate\"");
        serverSource.Should().Contain("path == \"/api/translations/highlight\"");
        serverSource.Should().Contain("ParseGlossaryFilterOptionsQuery");
        serverSource.Should().Contain("ParseGlossaryColumnFilters");
        serverSource.Should().Contain("OriginalSourceTerm");
        serverSource.Should().Contain("OriginalTargetLanguage");
        serverSource.Should().Contain("ParseTranslationFilterOptionsQuery");
        serverSource.Should().Contain("ParseColumnFilters");
        serverSource.Should().Contain("TranslationCacheColumns.EmptyValueMarker");
        pluginSource.Should().Contain("translation-glossary.sqlite");
        pluginSource.Should().Contain("SqliteGlossaryStore");
    }

    [Fact]
    public void Generated_control_panel_exposes_complete_glossary_table_controls()
    {
        var htmlSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "ControlPanelHtml.cs"));

        htmlSource.Should().Contain("glossaryColumnMenuButton");
        htmlSource.Should().Contain("glossaryColumnChooser");
        htmlSource.Should().Contain("clearGlossaryFilters");
        htmlSource.Should().Contain("saveGlossaryRows");
        htmlSource.Should().Contain("deleteSelectedGlossaryTerms");
        htmlSource.Should().Contain("glossaryContextMenu");
        htmlSource.Should().Contain("glossaryColumnFilterMenu");
        htmlSource.Should().Contain("/api/glossary/filter-options");
        htmlSource.Should().Contain("hunity.glossary.columnWidths");
        htmlSource.Should().Contain("data-glossary-action");
        htmlSource.Should().Contain("删除选中术语");
        htmlSource.Should().Contain("glossary-cell-center");
    }

    [Fact]
    public void Local_http_server_exposes_windows_font_picker_endpoint_without_persisting_config()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pickerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "WindowsFontFilePicker.cs"));

        serverSource.Should().Contain("context.Request.HttpMethod == \"POST\" && path == \"/api/fonts/pick\"");
        serverSource.Should().Contain("ReadJsonAsync<FontPickRequest>(context.Request)");
        serverSource.Should().Contain("CopyToConfig == true");
        serverSource.Should().Contain("CopyToFontConfigDirectory");
        serverSource.Should().NotContain("_controlPanel.UpdateConfig(new UpdateConfigRequest(ReplacementFont");
        pickerSource.Should().Contain("SetApartmentState(ApartmentState.STA)");
        pickerSource.Should().Contain("IFileOpenDialog");
        pickerSource.Should().Contain("*.ttf;*.otf");
        pickerSource.Should().Contain("FontNameReader.TryReadFamilyName");
        pickerSource.Should().Contain("FontPickResult.Unsupported");
        pickerSource.Should().Contain("FontPickResult.Cancelled");
    }

    [Fact]
    public void Windows_file_pickers_mark_com_dialog_paths_as_windows_only()
    {
        var fontPickerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "WindowsFontFilePicker.cs"));
        var modelPickerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "WindowsLlamaCppModelFilePicker.cs"));

        foreach (var pickerSource in new[] { fontPickerSource, modelPickerSource })
        {
            pickerSource.Should().Contain("using System.Runtime.Versioning;");
            pickerSource.Should().Contain("[SupportedOSPlatform(\"windows\")]");
            pickerSource.Should().Contain("[SupportedOSPlatformGuard(\"windows\")]");
            pickerSource.Should().Contain("if (!IsWindows())");
            pickerSource.Should().Contain("private static bool IsWindows()");
        }
    }

    [Fact]
    public void Local_http_server_exposes_llamacpp_manual_control_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var managerSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "LlamaCppServerManager.cs"));
        var commandBuilderSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Core", "Providers", "LlamaCppServerCommandBuilder.cs"));

        serverSource.Should().Contain("path == \"/api/llamacpp/start\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/stop\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/benchmark\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/model/pick\"");
        serverSource.Should().Contain("WindowsLlamaCppModelFilePicker.PickModelFile()");
        serverSource.Should().Contain("BenchmarkAsync(_controlPanel.GetConfig()");
        serverSource.Should().Contain("_controlPanel.UpdateConfig(new UpdateConfigRequest(LlamaCpp:");
        serverSource.Should().Contain("_controlPanel.SetLlamaCppAutoStartOnStartup(status.State != \"error\")");
        serverSource.Should().Contain("_controlPanel.SetLlamaCppAutoStartOnStartup(false)");
        serverSource.Should().Contain("_controlPanel.SetProviderProfileLlamaCppAutoStartOnStartup(profile.Id, status.State != \"error\")");
        serverSource.Should().Contain("_controlPanel.SetProviderProfileLlamaCppAutoStartOnStartup(profile.Id, false)");
        serverSource.Should().Contain("if (result.Succeeded && result.RecommendedConfig != null)");
        serverSource.Should().Contain("_controlPanel.UpdateProviderProfile(profile.Id, new ProviderProfileUpdateRequest(LlamaCpp: savedConfig))");
        commandBuilderSource.Should().Contain("\"--host\"");
        commandBuilderSource.Should().Contain("\"127.0.0.1\"");
        commandBuilderSource.Should().Contain("\"--metrics\"");
        commandBuilderSource.Should().Contain("int port");
        managerSource.Should().Contain("GetFreeLoopbackPort");
        managerSource.Should().Contain("CUDA_SCALE_LAUNCH_QUEUES");
        managerSource.Should().Contain("llama-bench.exe");
        managerSource.Should().Contain("llama-batched-bench.exe");
        managerSource.Should().Contain("Release");
        managerSource.Should().Contain("Variant");
        managerSource.Should().Contain("backend.json");
        managerSource.Should().Contain("llama-server.exe");
        managerSource.Should().Contain("StopOwnedProcess");
    }

    [Fact]
    public void Plugin_runtime_background_starts_llamacpp_when_saved_config_requests_it()
    {
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"));

        pluginSource.Should().Contain("StartLlamaCppIfConfigured()");
        pluginSource.Should().Contain("AutoStartOnStartup");
        pluginSource.Should().Contain("ProviderKind.LlamaCpp");
        pluginSource.Should().Contain("Task.Run");
        pluginSource.Should().Contain("_controlPanel.SetLlamaCppStatus(status)");
    }

    [Fact]
    public void Local_http_server_exposes_llamacpp_model_download_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"));

        serverSource.Should().Contain("path == \"/api/llamacpp/model/presets\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/model/download\"");
        serverSource.Should().Contain("path == \"/api/llamacpp/model/download/cancel\"");
        serverSource.Should().Contain("_llamaCppModelDownloads.GetPresets()");
        serverSource.Should().Contain("_llamaCppModelDownloads.StartDownload(");
        serverSource.Should().Contain("_llamaCppModelDownloads.CancelDownload()");
        pluginSource.Should().Contain("LlamaCppModelDownloadManager");
        pluginSource.Should().Contain("Path.Combine(pluginDirectory, \"models\")");
    }

    [Fact]
    public void Local_http_server_exposes_texture_export_import_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"));

        serverSource.Should().Contain("path == \"/api/textures/scan\"");
        serverSource.Should().Contain("path == \"/api/textures\"");
        serverSource.Should().Contain("path == \"/api/textures/export\"");
        serverSource.Should().Contain("path == \"/api/textures/import\"");
        serverSource.Should().Contain("path == \"/api/textures/overrides\"");
        serverSource.Should().Contain("ParseTextureCatalogQuery");
        serverSource.Should().Contain("path.StartsWith(\"/api/textures/\", StringComparison.Ordinal)");
        serverSource.Should().Contain("TryGetSourceImage");
        serverSource.Should().Contain("TryGetTextureImage");
        serverSource.Should().Contain("variant=source|override");
        serverSource.Should().Contain("context.Request.QueryString[\"scene\"]");
        serverSource.Should().Contain("ReadBytesAsync(context.Request)");
        serverSource.Should().Contain("request.ContentLength64");
        serverSource.Should().Contain("WriteBytesAsync(context.Response");
        serverSource.Should().Contain("Content-Disposition");
        serverSource.Should().Contain("response.OutputStream.Close()");
        serverSource.Should().Contain("new UTF8Encoding(false)");
        pluginSource.Should().Contain("texture-overrides");
        pluginSource.Should().Contain("texture-catalog");
        pluginSource.Should().Contain("UnityTextureReplacementService");
        pluginSource.Should().Contain("new LocalHttpServer(");
    }

    [Fact]
    public void Local_http_server_exposes_texture_image_provider_profile_endpoints()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var pluginSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"));

        serverSource.Should().Contain("path.StartsWith(\"/api/texture-image-profiles\", StringComparison.Ordinal)");
        serverSource.Should().Contain("HandleTextureImageProviderProfilesAsync");
        serverSource.Should().Contain("TextureImageProviderProfileUpdateRequest");
        serverSource.Should().Contain("/api/texture-image-profiles/import");
        serverSource.Should().Contain("move-up");
        serverSource.Should().Contain("move-down");
        serverSource.Should().Contain("export");
        serverSource.Should().Contain("test");
        serverSource.Should().Contain("models");
        serverSource.Should().Contain("balance");
        pluginSource.Should().Contain("texture-image-providers");
        pluginSource.Should().Contain("EncryptedTextureImageProviderProfileStore");
    }

    [Fact]
    public void Unity_texture_replacement_service_uses_safe_png_capture_and_runtime_replacement_paths()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextureReplacementService.cs"));

        serviceSource.Should().Contain("ImageConversion.EncodeToPNG");
        serviceSource.Should().Contain("ImageConversion.LoadImage");
        serviceSource.Should().Contain("RenderTexture.active");
        serviceSource.Should().Contain("finally");
        serviceSource.Should().Contain("ReadPixels");
        serviceSource.Should().Contain("RawImage");
        serviceSource.Should().Contain("Image.sprite");
        serviceSource.Should().Contain("SpriteRenderer");
        serviceSource.Should().Contain("renderer.sharedMaterial.mainTexture");
        serviceSource.Should().Contain("_appliedOverrides");
        serviceSource.Should().Contain("OverrideApplicationKey");
        serviceSource.Should().Contain("SkipAlreadyAppliedOverride");
        serviceSource.Should().NotContain("renderer.material.mainTexture");
        serviceSource.Should().Contain("sharedMaterial");
        serviceSource.Should().Contain("GenerateTextureImageWithFailoverAsync");
        serviceSource.Should().Contain("foreach (var profile in profiles)");
        serviceSource.Should().Contain("foreach (var visionProfile in visionProfiles)");
        serviceSource.Should().Contain("IsTextureImageProviderFailure");
        serviceSource.Should().Contain("ConcurrentQueue<Action>");
        serviceSource.Should().Contain("TaskCreationOptions.RunContinuationsAsynchronously");
        serviceSource.Should().Contain("SceneManager.GetActiveScene()");
        serviceSource.Should().Contain("TextureOverrideStore");
    }

    [Fact]
    public void Unity_texture_scan_runs_incrementally_and_uses_persistent_catalog()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextureReplacementService.cs"));

        serviceSource.Should().Contain("TextureCatalogStore");
        serviceSource.Should().Contain("TextureScanSession");
        serviceSource.Should().Contain("ProcessScanSlice");
        serviceSource.Should().Contain("MaxTextureScanTargetsPerTick");
        serviceSource.Should().Contain("_catalogStore.Upsert");
        serviceSource.Should().NotContain("return EnqueueOnMainThread(() => ScanOnMainThread(applyOverrides: true));");
    }

    [Fact]
    public void Unity_texture_scan_defers_large_textures_and_supports_sprite_subregions()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextureReplacementService.cs"));
        var modelsSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Core", "Textures", "TextureModels.cs"));
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));

        modelsSource.Should().Contain("TextureScanRequest");
        modelsSource.Should().Contain("IncludeDeferredLargeTextures");
        modelsSource.Should().Contain("DeferredTargetCount");
        modelsSource.Should().Contain("DeferredTextureCount");
        serverSource.Should().Contain("ReadJsonAsync<TextureScanRequest>");
        serviceSource.Should().Contain("MaxAutomaticTextureCapturePixels = 4096 * 4096");
        serviceSource.Should().Contain("MaxTextureScanTargetsPerTick = 1");
        serviceSource.Should().Contain("DeferredTargetCount");
        serviceSource.Should().Contain("DeferredTextureCount");
        serviceSource.Should().Contain("延迟扫描超大贴图");
        serviceSource.Should().Contain("TryGetSpriteTextureRect");
        serviceSource.Should().Contain("CropSpriteTextureRegion");
        serviceSource.Should().Contain("SpriteSubregionTextureTarget");
        serviceSource.Should().Contain("紧密打包图集暂不支持直接裁剪");
        serviceSource.Should().NotContain("跳过图集子区域贴图");
        serviceSource.Should().NotContain("跳过 SpriteRenderer 图集子区域贴图");
    }

    [Fact]
    public void Translation_editor_save_publishes_manual_writeback_for_known_targets()
    {
        var serverSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"));
        var highlighterSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextHighlighter.cs"));

        serverSource.Should().Contain("TryGetExistingTranslation(entry");
        serverSource.Should().Contain("PublishManualWriteback(entry, previousTranslatedText)");
        serverSource.Should().Contain("previousTranslatedText:");
        serverSource.Should().Contain("TryResolveTargetId");
        highlighterSource.Should().Contain("TryResolveTargetId");
    }

    [Fact]
    public void Font_replacement_service_retries_tmp_candidates_and_caches_failures()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        serviceSource.Should().Contain("_failedTmpFontAssetKeys");
        serviceSource.Should().Contain("ResolveTmpFontAsset");
        serviceSource.Should().Contain("EnumerateTmpFontCandidates");
        serviceSource.Should().Contain("EnumerateUnityFontCandidates");
        serviceSource.Should().Contain("foreach (var candidate in EnumerateTmpFontCandidates(config, key, context))");
        serviceSource.Should().Contain("无法用候选字体创建 TMP 后备字体");
        serviceSource.Should().Contain("Action<string?, string?> automaticFontFallbackReporter");
        serviceSource.Should().Contain("ReportAutomaticFontFallbacks(config);");
        serviceSource.Should().Contain("ResolveFirstUsableAutomaticFontFile");
        serviceSource.Should().Contain("FontProbeCharacters");
        serviceSource.Should().Contain("IsUsableReplacementFont(regularFont, size)");
        serviceSource.Should().Contain("font.RequestCharactersInTexture(new string(FontProbeCharacters), size)");
        serviceSource.Should().Contain("font.HasCharacter(character)");
    }

    [Fact]
    public void Tmp_font_replacement_supports_fallback_first_and_direct_assignment_fallback()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        serviceSource.Should().Contain("SetTmpFont(component, fontAsset)");
        serviceSource.Should().Contain("AddTmpFallbackToComponentFont(component, fontAsset)");
        serviceSource.Should().Contain("PopulateTmpFontAsset(fontAsset, component)");
        serviceSource.Should().Contain("method.Name == \"TryAddCharacters\"");
        serviceSource.Should().Contain("fallbackFontAssetTable");
        serviceSource.Should().Contain("m_FallbackFontAssetTable");
        serviceSource.Should().Contain("CollectionAdd(fallbackTable, fallbackFontAsset)");
        serviceSource.Should().Contain("AddTmpFallback(fontAsset)");
        serviceSource.Should().Contain("SetField(component, \"m_fontAsset\", fontAsset)");
        serviceSource.Should().Contain("SetField(component, \"m_currentFontAsset\", fontAsset)");
        serviceSource.Should().Contain("SetProperty(component, \"fontAsset\", fontAsset)");
        serviceSource.Should().Contain("SetProperty(component, \"fontSharedMaterial\", material)");
        serviceSource.Should().Contain("SetField(component, \"m_hasFontAssetChanged\", true)");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(component, \"LoadFontAsset\")");
        serviceSource.Should().Contain("SetProperty(component, \"havePropertiesChanged\", true)");
        serviceSource.Should().Contain("SetField(component, \"m_havePropertiesChanged\", true)");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(fontAsset, \"ReadFontAssetDefinition\")");
        serviceSource.Should().Contain("RegisterTmpFontAsset(fontAsset)");
        serviceSource.Should().Contain("MaterialReferenceManager");
        serviceSource.Should().Contain("method.Name == \"AddFontAsset\"");
        serviceSource.Should().Contain("InvokeSetter(instance, propertyName, value)");
        serviceSource.Should().Contain("method.Name == $\"get_{propertyName}\"");
        serviceSource.Should().Contain("method.Name == setterName");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(component, \"SetAllDirty\")");
        serviceSource.Should().Contain("InvokeMethodIfAvailable(component, \"ForceMeshUpdate\")");
        serviceSource.Should().Contain("AppDomain.CurrentDomain.GetAssemblies()");
        serviceSource.Should().Contain("TMP 全局后备字体未安装");
        serviceSource.Should().Contain("TMP 组件字体直接替换失败");
        serviceSource.Should().Contain("TMP 组件字体后备表已挂载");
    }

    [Fact]
    public void Tmp_font_replacement_preserves_original_material_when_fallbacks_are_available()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));
        var applyToTmpBlock = serviceSource[
            serviceSource.IndexOf("public void ApplyToTmp", StringComparison.Ordinal)..
            serviceSource.IndexOf("public void RestoreTmp", StringComparison.Ordinal)];

        applyToTmpBlock.Should().Contain("var componentFallbackInstalled = AddTmpFallbackToComponentFont(component, fontAsset);");
        applyToTmpBlock.Should().Contain("var globalFallbackInstalled = AddTmpFallback(fontAsset);");
        applyToTmpBlock.Should().Contain("if (!componentFallbackInstalled && !globalFallbackInstalled)");
        applyToTmpBlock.IndexOf("AddTmpFallbackToComponentFont(component, fontAsset)", StringComparison.Ordinal)
            .Should().BeLessThan(applyToTmpBlock.IndexOf("SetTmpFont(component, fontAsset)", StringComparison.Ordinal));
        applyToTmpBlock.IndexOf("AddTmpFallback(fontAsset)", StringComparison.Ordinal)
            .Should().BeLessThan(applyToTmpBlock.IndexOf("SetTmpFont(component, fontAsset)", StringComparison.Ordinal));

        var addGlobalFallbackBlock = serviceSource[
            serviceSource.IndexOf("private bool AddTmpFallback(object fontAsset)", StringComparison.Ordinal)..
            serviceSource.IndexOf("private static bool AddTmpFallbackToComponentFont", StringComparison.Ordinal)]
            .Replace("\r\n", "\n");
        addGlobalFallbackBlock.Should().Contain("if (fallbacks.Contains(fontAsset))\n        {\n            return true;\n        }");
    }

    [Fact]
    public void Font_replacement_keeps_original_component_fonts_when_translated_text_is_supported()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));
        var uguiBlock = serviceSource[
            serviceSource.IndexOf("public void ApplyToUgui", StringComparison.Ordinal)..
            serviceSource.IndexOf("public void RestoreUgui", StringComparison.Ordinal)];
        var tmpBlock = serviceSource[
            serviceSource.IndexOf("public void ApplyToTmp", StringComparison.Ordinal)..
            serviceSource.IndexOf("public void RestoreTmp", StringComparison.Ordinal)];

        uguiBlock.Should().Contain("string translatedText");
        tmpBlock.Should().Contain("string translatedText");
        uguiBlock.Should().Contain("OriginalUguiFontCanRenderText(component, translatedText)");
        tmpBlock.Should().Contain("OriginalTmpFontCanRenderText(component, translatedText)");
        uguiBlock.IndexOf("OriginalUguiFontCanRenderText(component, translatedText)", StringComparison.Ordinal)
            .Should().BeLessThan(uguiBlock.IndexOf("ResolveUnityTextFont(config, key, context", StringComparison.Ordinal));
        tmpBlock.IndexOf("OriginalTmpFontCanRenderText(component, translatedText)", StringComparison.Ordinal)
            .Should().BeLessThan(tmpBlock.IndexOf("ResolveTmpFontAsset(config, key, context", StringComparison.Ordinal));
    }

    [Fact]
    public void Tmp_font_replacement_prepares_fallback_tables_before_direct_assignment()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));
        var applyToTmpBlock = serviceSource[
            serviceSource.IndexOf("public void ApplyToTmp", StringComparison.Ordinal)..
            serviceSource.IndexOf("public void RestoreTmp", StringComparison.Ordinal)];

        applyToTmpBlock.Should().Contain("var samplingPointSize = ResolveComponentFontSamplingPointSize(component, config);");
        applyToTmpBlock.Should().Contain("ResolveTmpFontAsset(config, key, context, samplingPointSize, out _)");
        serviceSource.Should().Contain("EnsureTmpFallbackTable(targetFontAsset)");
        serviceSource.Should().Contain("SetProperty(targetFontAsset, \"fallbackFontAssetTable\", createdTable)");
        serviceSource.Should().Contain("SetField(targetFontAsset, \"m_FallbackFontAssetTable\", createdTable)");
        serviceSource.Should().Contain("private static bool TmpFontAssetCanRenderText(object? fontAsset, string text");
        applyToTmpBlock.IndexOf("AddTmpFallbackToComponentFont(component, fontAsset)", StringComparison.Ordinal)
            .Should().BeLessThan(applyToTmpBlock.IndexOf("SetTmpFont(component, fontAsset)", StringComparison.Ordinal));
    }

    [Fact]
    public void Ugui_font_replacement_prefers_manual_file_before_os_font_names_while_tmp_keeps_file_candidates()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        var uguiBlock = serviceSource[
            serviceSource.IndexOf("public void ApplyToUgui", StringComparison.Ordinal)..
            serviceSource.IndexOf("public void RestoreUgui", StringComparison.Ordinal)];
        var imguiBlock = serviceSource[
            serviceSource.IndexOf("public void ApplyToImgui", StringComparison.Ordinal)..
            serviceSource.IndexOf("public void RestoreImgui", StringComparison.Ordinal)];

        serviceSource.Should().Contain("private static readonly string[] CandidateFontNames");
        serviceSource.Should().Contain("foreach (var fontName in CandidateFontNames)");
        serviceSource.Should().Contain("private IEnumerable<FontCandidate> EnumerateUnityFontCandidates");
        serviceSource.Should().Contain("private IEnumerable<FontCandidate> EnumerateTmpFontCandidates");
        uguiBlock.Should().Contain("ResolveUnityTextFont(config, key, context");
        imguiBlock.Should().Contain("ResolveCachedImguiFont(config, key, context");
        serviceSource.Should().Contain("var resolved = ResolveUnityTextFont(config, key, context, fontSize);");
        serviceSource.Should().Contain("foreach (var candidate in EnumerateTmpFontCandidates(config, key, context))");

        var uguiCandidateBlock = serviceSource[
            serviceSource.IndexOf("private IEnumerable<FontCandidate> EnumerateUnityFontCandidates", StringComparison.Ordinal)..
            serviceSource.IndexOf("private IEnumerable<FontCandidate> EnumerateTmpFontCandidates", StringComparison.Ordinal)];
        uguiCandidateBlock.IndexOf("FontCandidate.Create(\"file\", config.ReplacementFontFile", StringComparison.Ordinal)
            .Should().BeLessThan(uguiCandidateBlock.IndexOf("FontCandidate.Create(\"name\", config.ReplacementFontName", StringComparison.Ordinal));
        serviceSource.Should().Contain("Font.GetOSInstalledFontNames()");

        var createUnityFontBlock = serviceSource[
            serviceSource.IndexOf("private static Font? CreateUnityFont(FontCandidate candidate, int size)", StringComparison.Ordinal)..
            serviceSource.IndexOf("private static Font? CreateUnityFont(string value, int size)", StringComparison.Ordinal)];
        createUnityFontBlock.Should().Contain("candidate.Source == \"file\"");
        createUnityFontBlock.Should().Contain("candidate.Source == \"name\"");
        createUnityFontBlock.Should().NotContain("Font.CreateDynamicFontFromOSFont(candidate.Value");
    }

    [Fact]
    public void Imgui_font_replacement_guards_gui_skin_access_outside_on_gui()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));
        var imguiBlock = serviceSource[
            serviceSource.IndexOf("public void ApplyToImgui", StringComparison.Ordinal)..
            serviceSource.IndexOf("public void RestoreImgui", StringComparison.Ordinal)];
        var restoreBlock = serviceSource[
            serviceSource.IndexOf("private int RestoreImguiFont", StringComparison.Ordinal)..
            serviceSource.IndexOf("private static bool TryGetImguiSkin", StringComparison.Ordinal)];

        serviceSource.Should().Contain("private static bool TryGetImguiSkin(out GUISkin skin)");
        serviceSource.Should().Contain("catch (ArgumentException)");
        serviceSource.Should().Contain("private static int ResolveImguiFontPointSize(GUISkin skin, RuntimeConfig config)");
        serviceSource.Should().Contain("ResolveImguiFontPointSize(skin, config)");
        serviceSource.Should().Contain("return 16;");
        imguiBlock.Should().Contain("TryGetImguiSkin(out var skin)");
        imguiBlock.Should().NotContain("Math.Max(1, config.FontSamplingPointSize)");
        imguiBlock.Should().NotContain("GUI.skin");
        restoreBlock.Should().Contain("TryGetImguiSkin(out var skin)");
        restoreBlock.Should().NotContain("GUI.skin");
    }

    [Fact]
    public void Plugin_console_logs_use_simple_chinese_messages()
    {
        var logSources = new[]
        {
            FindRepositoryFile("src", "HUnityAutoTranslator.Core", "Queueing", "TranslationWorkerPool.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Plugin.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "PluginRuntime.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "TranslationWorkerHost.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "LlamaCppServerManager.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "SystemBrowserLauncher.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Web", "LocalHttpServer.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Hotkeys", "RuntimeHotkeyController.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Capture", "UguiTextScanner.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Capture", "TmpTextScanner.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Capture", "ImguiHookInstaller.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityMainThreadResultApplier.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"),
            FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextHighlighter.cs")
        };
        var combinedSource = string.Join("\n", logSources.Select(File.ReadAllText));
        var oldEnglishLogPhrases = new[]
        {
            "Control panel auto-open skipped because the URL is empty.",
            "Opened control panel in the system default browser",
            "Failed to open control panel in the system default browser",
            "HTTP panel listener failed",
            "Control panel config updated.",
            "Control panel API key cleared.",
            "Control panel API key configured.",
            "HTTP panel request failed",
            "llama.cpp server process exited.",
            "llama.cpp server started on random loopback port",
            "Stopping llama.cpp server failed",
            "Resumed ",
            "pending translation(s) from the persistent cache.",
            "Translation worker processed",
            "Writeback backlog",
            "Cache entries",
            "Translation worker failed",
            "Glossary extraction imported",
            "loaded. Control panel",
            "Persistent settings",
            "Translation cache",
            "Translation glossary",
            "Startup failed, plugin will stay inactive",
            "Control panel auto-open is disabled by settings.",
            "translated text result(s).",
            "targets were gone or changed before writeback.",
            "Highlight target disappeared before it could be drawn",
            "UGUI Text type not found; UGUI capture disabled.",
            "UGUI capture enabled.",
            "UGUI scan failed and will retry later",
            "TextMeshPro type not found; TMP capture disabled.",
            "TMP capture enabled with type",
            "TMP scan failed; TMP capture disabled",
            "IMGUI capture enabled.",
            "IMGUI hook installation failed; IMGUI capture disabled",
            "Failed to patch",
            "Runtime hotkey switched text display",
            "Runtime hotkey forced a full text scan",
            "Runtime hotkey switched text components",
            "Runtime hotkey restored original text component fonts",
            "TMP fallback font installed",
            "Font replacement skipped because the font could not be created",
            "Font replacement is enabled, but no usable CJK fallback font was found.",
            "TMP font replacement skipped because TextMeshPro settings or font asset APIs were not available.",
            "TMP fallback font asset could not be created from any candidate.",
            "Font size adjusted for",
            "Translation output rejected",
            "Translation provider failed",
            "Source preview",
            "unknown error"
        };

        combinedSource.Should().NotContainAny(oldEnglishLogPhrases);
    }

    [Fact]
    public void Translation_worker_host_uses_failover_provider_for_ready_profile_queue()
    {
        var hostSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "TranslationWorkerHost.cs"));

        hostSource.Should().Contain("if (_controlPanel.HasReadyProviderRuntimeProfile())");
        hostSource.Should().Contain("return new FailoverTranslationProvider(");
        hostSource.Should().Contain("return CreateLegacyProvider(config);");
        hostSource.Should().Contain("ProviderProfilesReadyAsync(config, cancellationToken)");
        hostSource.Should().Contain("runtimeProfile.LlamaCpp?.AutoStartOnStartup == true");
        hostSource.Should().Contain("return new PendingTranslationProvider(runtimeProfile.Profile, message);");
        hostSource.Should().Contain("if (profile.Profile.Kind == ProviderKind.LlamaCpp)");
    }

    [Fact]
    public void Font_replacement_automatic_candidates_preserve_priority_and_use_regular_face_for_variable_fonts()
    {
        var serviceSource = File.ReadAllText(FindRepositoryFile("src", "HUnityAutoTranslator.Plugin", "Unity", "UnityTextFontReplacementService.cs"));

        var candidateFileBlock = serviceSource[
            serviceSource.IndexOf("private static readonly string[] CandidateFontFiles", StringComparison.Ordinal)..
            serviceSource.IndexOf("private static readonly string[] TmpFontAssetTypeNames", StringComparison.Ordinal)];

        candidateFileBlock.Should().Contain(@"C:\Windows\Fonts\NotoSansSC-VF.ttf");
        candidateFileBlock.Should().Contain(@"C:\Windows\Fonts\Deng.ttf");
        candidateFileBlock.IndexOf(@"C:\Windows\Fonts\simhei.ttf", StringComparison.Ordinal)
            .Should().BeLessThan(candidateFileBlock.IndexOf(@"C:\Windows\Fonts\Deng.ttf", StringComparison.Ordinal));
        candidateFileBlock.IndexOf(@"C:\Windows\Fonts\Deng.ttf", StringComparison.Ordinal)
            .Should().BeLessThan(candidateFileBlock.IndexOf(@"C:\Windows\Fonts\NotoSansSC-VF.ttf", StringComparison.Ordinal));
        candidateFileBlock.Should().Contain(".ttf");
        candidateFileBlock.Should().NotContain(".ttc");
        serviceSource.Should().Contain("private static readonly string[] CandidateFontNames");
        serviceSource.Should().Contain("FontCandidate.Create(\"auto-name\"");
        serviceSource.Should().Contain("Noto Sans SC Regular");
        serviceSource.Should().Contain("Noto Serif SC Regular");
        serviceSource.Should().Contain("FontCandidate.Create(\"auto-file\"");
        var tmpCandidateBlock = serviceSource[
            serviceSource.IndexOf("private IEnumerable<FontCandidate> EnumerateTmpFontCandidates", StringComparison.Ordinal)..
            serviceSource.IndexOf("private ResolvedFont? ResolveExplicitFont", StringComparison.Ordinal)];
        tmpCandidateBlock.Should().NotContain("FontCandidate.Create(\"auto-name\"");
    }

    private static string FindRepositoryFile(params string[] relativeSegments)
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "HUnityAutoTranslator.sln")))
        {
            directory = directory.Parent;
        }

        directory.Should().NotBeNull("tests should run from inside the repository checkout");
        return Path.Combine(new[] { directory!.FullName }.Concat(relativeSegments).ToArray());
    }
}
